insert into colleges (name, slug, endorsement_status) values ('BMSIT&M','bmsitm','approved'), ('MSRIT','msrit','approved') on conflict (slug) do nothing;
insert into alumni_profiles (college_id,name,initials,company,role,years_experience,expertise,rate_call_10min,rate_call_30min,rate_full_unlock,rating,is_verified,is_published,free_summary_text,full_roadmap_text)
select c.id, v.name,v.initials,v.company,v.role,v.years,v.expertise,v.rate10,v.rate30,249,v.rating,true,true,v.summary,v.roadmap from (values
('BMSIT&M','Aarav Mehta','AM','Google','Senior Software Engineer','7 years',array['Product engineering','System design'],599,999,4.9,'A practical overview of growing into a senior engineering role at Google, with an emphasis on product impact and clear technical communication.','A focused roadmap for strengthening product engineering fundamentals, system design judgment, and interview readiness for large technology companies.'),
('MSRIT','Nisha Rao','NR','Microsoft','Product Manager','6 years',array['Product strategy','Career switch'],539,899,4.9,'A guide to product thinking at Microsoft, connecting customer problems, strategy, and a credible path into product management.','A step-by-step product career roadmap covering structured problem solving, portfolio stories, and preparation for product interviews.'),
('BMSIT&M','Karthik Iyer','KI','Amazon','SDE II','5 years',array['Interview prep','DSA'],479,799,4.8,'An honest account of building software engineering depth at Amazon through deliberate interview preparation and execution.','A practical plan for DSA fluency, system design basics, project storytelling, and consistent applications.'),
('MSRIT','Ananya Sharma','AS','Atlassian','Data Scientist','5 years',array['Data science','Portfolios'],539,899,5.0,'An approachable view of data science at Atlassian, including how strong portfolios show both analytical rigor and product context.','A roadmap for selecting data projects, communicating insights, and preparing for data science interviews.'),
('BMSIT&M','Rohan Desai','RD','Razorpay','UX Designer','4 years',array['Design careers','Portfolio review'],419,699,4.8,'A portfolio-led introduction to UX design at Razorpay, balancing visual craft, user research, and business constraints.','A clear plan for producing case studies, seeking feedback, and presenting a design portfolio with confidence.'),
('MSRIT','Meera Nair','MN','Flipkart','Engineering Manager','9 years',array['Leadership','Backend'],719,1199,4.9,'A perspective on backend engineering and leadership at Flipkart, including the habits that compound as responsibility grows.','A progression plan for backend foundations, system ownership, communication, and emerging technical leadership.')
) as v(college_name,name,initials,company,role,years,expertise,rate10,rate30,rating,summary,roadmap) join colleges c on c.name=v.college_name;
