'use client'
// Client components: migrated landing page sections.
import {useState} from 'react';import {useRouter} from 'next/navigation';import Avatar from '@/components/ui/Avatar';import ComingSoon from '@/components/ui/ComingSoon';import {comingColleges,liveColleges,mentors} from '@/lib/types'
export function HeroSection(){const r=useRouter();return <section className="editorial-hero"><div className="hero-copy"><div className="pill">MENTOR-LED CAREER ACCELERATION</div><h1>Your college network.<br/>Your career <em>playbook.</em></h1><p>VantiqLabs connects ambitious engineering students with verified alumni who have already built the careers they want.</p><div className="hero-actions"><button className="outline-cta" onClick={()=>r.push('/browse')}>View mentor network</button><button className="dark-cta" onClick={()=>r.push('/browse')}>Start exploring →</button></div></div><div className="product-frame"><div className="browser-bar"><i/><i/><i/><span>vantiqlabs.in</span></div><div className="mini-product"><div className="mini-nav"><b>✦ VantiqLabs</b><span>Mentors</span><span>Roadmaps</span></div><p>Find someone who knows the way.</p><h3>Meet mentors who built<br/>the careers you want.</h3></div></div></section>}
export function CampusMarquee(){const r=useRouter(),[soon,setSoon]=useState<string|null>(null),names=[...liveColleges,...comingColleges.map(x=>x[0])];return <><section className="campus-marquee"><p>Growing across Bengaluru&apos;s engineering colleges</p><div className="marquee-window"><div className="marquee-track">{[0,1].map(g=><div className="marquee-group" key={g}>{names.map(n=><button key={g+n} onClick={()=>liveColleges.includes(n as never)?r.push('/browse?college='+encodeURIComponent(n)):setSoon(n)} className={liveColleges.includes(n as never)?'campus-logo live':'campus-logo'}><i>{n.slice(0,3)}</i><b>{n}</b><span>{liveColleges.includes(n as never)?'MENTORS LIVE':'COMING SOON'}</span></button>)}</div>)}</div></div></section>{soon&&<ComingSoon name={soon} close={()=>setSoon(null)}/>}</>}
export function CompanyMarquee(){const c=['Airbus','Google','ABB','Siemens','TCS','Amazon','Microsoft','Walmart','Accenture','IBM','Cisco'];return <section className="company-marquee"><p>Companies our mentors have experience with</p><div className="marquee-window"><div className="marquee-track reverse">{[0,1].map(g=><div className="marquee-group" key={g}>{c.map(n=><div className="company-logo" key={g+n}><i>{n.slice(0,2)}</i><b>{n}</b></div>)}</div>)}</div></div></section>}
export function Comparison(){return <section className="comparison"><div className="editorial-heading"><span>THE DIFFERENCE</span><h2>How career planning feels<br/>before and after VantiqLabs.</h2><p>Less noise. More evidence. A person who has actually done it.</p></div><img src="/assets/career-clarity-comparison.png" alt="Career clarity comparison"/><div className="compare-grid"><div><small>WITHOUT VANTIQ</small><h3>Scattered advice</h3><p>Conflicting videos and endless guessing.</p></div><div><small>WITH VANTIQ</small><h3>A path built for you</h3><p>Relevant mentors and clear next steps.</p></div></div></section>}
export function FeatureShowcase(){return <><section className="feature-intro"><span>MEET VANTIQ</span><h2>Everything between ambition<br/>and an offer—made clearer.</h2></section><section className="feature-showcase">{[['01 · DISCOVER','Mentor match engine','Find college-relevant people whose direction matches your goal.'],['02 · LEARN','Career playbooks','Turn a real journey into practical, visible milestones.'],['03 · CONNECT','Focused 1:1 sessions','Book time when context and honest feedback matter.']].map(([n,h,p],i)=><article className="sticky-feature" key={h}><div className="feature-visual"><b>{i+1}</b><h3>{h}</h3></div><div className="feature-copy"><span>{n}</span><h2>{h}</h2><p>{p}</p></div></article>)}</section></>}
export function MentorEconomy(){return <section className="mentor-economy"><div className="editorial-heading"><span>FOR ALUMNI</span><h2>Turn experience into impact.</h2></div><div className="economy-grid"><div className="benefit-stack">{['Earn on your terms','Build meaningful influence','Stay in control'].map(x=><article key={x}><b>✦</b><h3>{x}</h3><p>Share practical experience with students from your campus.</p></article>)}</div><blockquote>“The best guidance comes from someone only a few years ahead.”<footer><Avatar mentor={mentors[1]} small/><div><b>Nisha Rao</b><span>MSRIT alumna · Product at Microsoft</span></div></footer></blockquote></div></section>}
export function Outcomes(){return <section className="outcomes"><div className="editorial-heading"><span>WHAT CHANGES</span><h2>Clarity compounds quickly.</h2></div><div className="timeline">{[['Today','Stop guessing'],['30 days','Build the right proof'],['90 days','Move with confidence']].map(([a,b])=><div key={a}><b>{a}</b><article><h3>{b}</h3><p>Take the next move with relevant context.</p></article></div>)}</div></section>}
export function Scale(){return <section className="scale"><div className="editorial-heading"><span>BUILT TO GROW</span><h2>Small network. Serious depth.</h2></div><div className="scale-grid">{[['2','COLLEGES LIVE'],['6','FOUNDING MENTORS'],['8','CAMPUSES NEXT'],['1:1','HUMAN CONTEXT']].map(([a,b])=><article key={b}><b>{a}</b><span>{b}</span><p>Built around trusted communities.</p></article>)}</div></section>}
export function Voices(){return <section className="voices"><div className="editorial-heading"><span>EARLY VOICES</span><h2>What students want from career guidance.</h2></div><div className="voice-grid">{['I need someone to tell me what mattered when they were in my place.','Seeing a senior from my college makes the path feel real.','The value is knowing what to ignore and what to do next.'].map((q,i)=><blockquote key={q}><p>“{q}”</p><footer>Student · {i?'MSRIT':'BMSIT&M'}</footer></blockquote>)}</div></section>}
export function FAQ(){const [open,setOpen]=useState(0),items=[['Who is VantiqLabs for?','Engineering students and alumni who want practical guidance.'],['How are mentors verified?','College and professional experience are reviewed.'],['Which colleges are live?','BMSIT&M and MSRIT are live first.']];return <section className="faq-section"><div className="editorial-heading"><span>QUESTIONS, ANSWERED</span><h2>Frequently asked questions.</h2></div><div className="faq-list">{items.map(([q,a],i)=><article className={open===i?'open':''} key={q}><button onClick={()=>setOpen(open===i?-1:i)}><b>{q}</b><i>↓</i></button><div><p>{a}</p></div></article>)}</div></section>}
export function MentorOrbit(){const r=useRouter(),p=['mentor-airbus.png','mentor-google.png','mentor-product.png','mentor-data.png','mentor-electrical.png','mentor-design.png','mentor-security.png','mentor-manager.png'];return <section className="mentor-orbit"><div className="orbit-stage"><div className="orbit-arc"/>{p.map((x,i)=><img key={x} src={'/assets/'+x} alt="VantiqLabs mentor" style={{animationDelay:`-${i*4}s`}}/>)}</div><div className="orbit-center"><span>PEOPLE, NOT NOISE</span><h2>Career clarity is<br/>closer than it feels.</h2><p>Meet alumni who understand your starting point.</p><button className="dark-cta" onClick={()=>r.push('/browse')}>Meet your mentors →</button></div></section>}
