import { useMemo, useState } from 'react'
import { comingColleges, liveColleges, mentors, type Mentor } from './data'

type Page = 'home' | 'browse' | 'profile' | 'booking' | 'dashboard' | 'signin' | 'signup'
const Icon = ({children}:{children:string}) => <span className="icon" aria-hidden="true">{children}</span>
const Avatar = ({mentor,small=false}:{mentor:Mentor;small?:boolean}) => <div className={'avatar '+(small?'small':'')} style={{background:mentor.color}}>{mentor.initials}</div>

export default function App(){
  const [page,setPage]=useState<Page>('home'), [selected,setSelected]=useState<Mentor>(mentors[0]), [saved,setSaved]=useState<number[]>([])
  const [query,setQuery]=useState(''), [college,setCollege]=useState<string>('All colleges'), [soon,setSoon]=useState<string|null>(null)
  const [mobileNav,setMobileNav]=useState(false)
  const goProfile=(m:Mentor)=>{setSelected(m);setPage('profile');window.scrollTo(0,0)}
  const goBrowse=()=>{setPage('browse');window.scrollTo(0,0)}
  const toggleSave=(id:number)=>setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])
  const nav=(target:Page)=>{setPage(target);setMobileNav(false);window.scrollTo(0,0)}
  if(page==='signin'||page==='signup')return <AuthScreen mode={page} switchMode={(mode)=>nav(mode)} back={()=>nav('home')}/>
  return <><header className="topbar"><button className="brand" onClick={()=>nav('home')}><b>✦</b> VantiqLabs</button><nav className={mobileNav?'open':''}><button onClick={goBrowse}>Find mentors</button><button onClick={()=>nav('dashboard')}>How it works</button><button onClick={goBrowse}>Pricing</button><button onClick={goBrowse}>Resources</button><button className="login" onClick={()=>nav('signin')}>Sign in</button><button className="signup-nav" onClick={()=>nav('signup')}>Sign up</button><button className="btn small-btn" onClick={goBrowse}>Get started</button></nav><button className="menu" onClick={()=>setMobileNav(!mobileNav)}>☰</button></header>
  {page==='home'&&<Home query={query} setQuery={setQuery} college={college} setCollege={setCollege} browse={goBrowse} setSoon={setSoon} />}
  {page==='browse'&&<Browse query={query} setQuery={setQuery} college={college} setCollege={setCollege} goProfile={goProfile} saved={saved} toggleSave={toggleSave} setSoon={setSoon}/>} 
  {page==='profile'&&<Profile mentor={selected} back={goBrowse} book={()=>nav('booking')} saved={saved.includes(selected.id)} toggleSave={()=>toggleSave(selected.id)}/>}
  {page==='booking'&&<Booking mentor={selected} done={()=>nav('dashboard')}/>} 
  {page==='dashboard'&&<Dashboard goBrowse={goBrowse} goProfile={goProfile} saved={saved}/>} 
  {soon&&<ComingSoon name={soon} close={()=>setSoon(null)}/>}<footer><span>✦ VantiqLabs</span><span>Built for ambitious students and exceptional mentors.</span></footer></>
}

function Home({query,setQuery,college,setCollege,browse,setSoon}:{query:string;setQuery:(x:string)=>void;college:string;setCollege:(x:string)=>void;browse:()=>void;setSoon:(x:string)=>void}){
  const choose=(v:string)=>{setCollege(v); if(!liveColleges.includes(v as never)&&v!=='All colleges')setSoon(v); else browse()}
  const campusNames=[...liveColleges,...comingColleges.map(x=>x[0])]
  const companies=['Airbus','Google','ABB','Siemens','TCS','Amazon','Microsoft','Walmart','Accenture','IBM','Cisco']
  return <main className="editorial-home">
    <section className="editorial-hero"><div className="hero-copy"><div className="pill">MENTOR-LED CAREER ACCELERATION</div><h1>Your college network.<br/>Your career <em>playbook.</em></h1><p>VantiqLabs connects ambitious engineering students with verified alumni who have already built the careers they want.</p><div className="hero-actions"><button className="outline-cta" onClick={browse}>View mentor network</button><button className="dark-cta" onClick={browse}>Start exploring →</button></div><div className="hero-proof"><span>✓ College-verified</span><span>✓ Practical roadmaps</span><span>✓ 1:1 guidance</span></div></div><ProductPreview query={query} setQuery={setQuery} browse={browse}/></section>
    <section className="campus-marquee"><p>Growing across Bengaluru's engineering colleges</p><div className="marquee-window"><div className="marquee-track">{[...campusNames,...campusNames].map((name,i)=><button key={`${name}-${i}`} onClick={()=>choose(name)} className={liveColleges.includes(name as never)?'campus-logo live':'campus-logo'}><i>{name.replace(/[^A-Z&]/g,'').slice(0,3)||name.slice(0,2).toUpperCase()}</i><b>{name}</b><span>{liveColleges.includes(name as never)?'MENTORS LIVE':'COMING SOON'}</span></button>)}</div></div></section>
    <section className="company-marquee"><p>Companies our mentors have experience with</p><div className="marquee-window"><div className="marquee-track reverse">{[...companies,...companies].map((name,i)=><div key={`${name}-${i}`} className={`company-logo company-${name.toLowerCase()}`}><i>{name.slice(0,2).toUpperCase()}</i><b>{name}</b></div>)}</div></div></section>
    <section className="comparison"><div className="editorial-heading"><span>THE DIFFERENCE</span><h2>How career planning feels<br/>before and after VantiqLabs.</h2><p>Less noise. More evidence. A person who has actually done it.</p></div><img src="/assets/career-clarity-comparison.png" alt="A student overwhelmed by career advice compared with a student following a mentor-led roadmap"/><div className="compare-grid"><div><small>WITHOUT VANTIQ</small><h3>Scattered advice</h3><p>Conflicting videos, generic roadmaps, and endless guessing about what companies actually expect.</p></div><div><small>WITH VANTIQ</small><h3>A path built for you</h3><p>College-relevant mentors, real career journeys, and clear next steps grounded in experience.</p></div></div></section>
    <section className="feature-intro"><span>MEET VANTIQ</span><h2>Everything between ambition<br/>and an offer—made clearer.</h2><p>One focused platform for discovering the right people, learning their playbooks, and getting personal guidance.</p></section>
    <section className="feature-showcase">
      <article className="sticky-feature"><FeatureVisual type="match"/><div className="feature-copy"><span>01 · DISCOVER</span><h2>Mentor match engine</h2><p>Filter by college, role, company, and expertise. Find people whose starting point looks like yours—and whose destination looks like your goal.</p><ul><li>Verified BMSIT&M and MSRIT alumni</li><li>Role and skill-based discovery</li><li>Save and compare mentors</li></ul></div></article>
      <article className="sticky-feature"><FeatureVisual type="roadmap"/><div className="feature-copy"><span>02 · LEARN</span><h2>Career playbooks</h2><p>Turn a mentor's real journey into a practical sequence: foundations, projects, interview preparation, applications, and the lessons no course teaches.</p><ul><li>Milestone-based roadmaps</li><li>Curated resources and interview notes</li><li>Progress that stays visible</li></ul></div></article>
      <article className="sticky-feature"><FeatureVisual type="session"/><div className="feature-copy"><span>03 · CONNECT</span><h2>Focused 1:1 sessions</h2><p>Book time when context matters. Bring a decision, portfolio, resume, or interview challenge—and leave with concrete next actions.</p><ul><li>Transparent availability and pricing</li><li>Structured session agenda</li><li>Action summary after every call</li></ul></div></article>
    </section>
    <section className="mentor-economy"><div className="editorial-heading"><span>FOR ALUMNI</span><h2>Turn experience into impact.</h2><p>Share what worked, guide students from your campus, and earn for high-value time.</p></div><div className="economy-grid"><div className="benefit-stack"><article><b>₹</b><h3>Earn on your terms</h3><p>Set availability and session pricing around your schedule.</p></article><article><b>↗</b><h3>Build meaningful influence</h3><p>Help students avoid the mistakes you had to learn firsthand.</p></article><article><b>⌁</b><h3>Stay in control</h3><p>Your profile, calendar, and knowledge remain yours.</p></article></div><blockquote>“The best guidance I received came from someone only a few years ahead of me. VantiqLabs makes that kind of conversation available to every serious student.”<footer><Avatar mentor={mentors[1]} small/><div><b>Nisha Rao</b><span>MSRIT alumna · Product at Microsoft</span></div></footer></blockquote></div></section>
    <section className="outcomes"><div className="editorial-heading"><span>WHAT CHANGES</span><h2>Clarity compounds quickly.</h2><p>A better decision today becomes a stronger profile, interview, and career move tomorrow.</p></div><div className="timeline"><div><b>Today</b><article><h3>Stop guessing</h3><p>See relevant mentors and proven routes from your own college network.</p></article></div><div><b>30 days</b><article><h3>Build the right proof</h3><p>Focus projects, skills, and applications around a deliberate roadmap.</p></article></div><div><b>90 days</b><article><h3>Move with confidence</h3><p>Interview with context, sharper stories, and mentor-tested preparation.</p></article></div></div></section>
    <section className="scale"><div className="editorial-heading"><span>BUILT TO GROW</span><h2>Small network. Serious depth.</h2><p>We begin with trusted campus communities, then expand without losing relevance.</p></div><div className="scale-grid">{[['2','COLLEGES LIVE','Deep mentor networks before broad expansion'],['6','FOUNDING MENTORS','Real operators across engineering, product, design, and data'],['8','CAMPUSES NEXT','Students can join the early-access list today'],['1:1','HUMAN CONTEXT','Technology makes discovery fast; people make guidance useful']].map(([n,l,d])=><article key={l}><b>{n}</b><span>{l}</span><p>{d}</p></article>)}</div></section>
    <section className="voices"><div className="editorial-heading"><span>EARLY VOICES</span><h2>What students want from career guidance.</h2></div><div className="voice-grid">{[['“I do not need another generic DSA list. I need someone to tell me what mattered when they were in my place.”','Student · BMSIT&M'],['“Seeing a senior from my own college at a company I admire makes the path feel real.”','Student · MSRIT'],['“The value is not more content—it is knowing what to ignore and what to do next.”','Final-year engineering student'],['“A focused thirty-minute conversation can replace weeks of second-guessing.”','Aspiring product engineer'],['“I want feedback on my actual portfolio, not another article about portfolios.”','Design student'],['“If the mentor understands my college context, the advice becomes immediately more useful.”','Second-year engineering student']].map(([q,n])=><blockquote key={n}><p>{q}</p><footer>{n}</footer></blockquote>)}</div></section>
    <FAQ/>
    <MentorOrbit browse={browse}/>
    <section className="final-cta"><span>YOUR NEXT MOVE CAN BE CLEARER</span><h2>Find the person who has<br/>already walked your path.</h2><button className="dark-cta" onClick={browse}>Explore VantiqLabs →</button></section>
  </main>
}

function ProductPreview({query,setQuery,browse}:{query:string;setQuery:(x:string)=>void;browse:()=>void}){return <div className="product-frame"><div className="browser-bar"><i/><i/><i/><span>vantiqlabs.in</span></div><div className="mini-product"><div className="mini-nav"><b>✦ VantiqLabs</b><span>Mentors</span><span>Roadmaps</span><span>Sessions</span></div><p>Find someone who knows the way.</p><h3>Meet mentors who built<br/>the careers you want.</h3><div className="mini-search"><Icon>⌕</Icon><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search role, company, or skill"/><button onClick={browse}>Search</button></div><div className="mini-list">{mentors.slice(0,2).map(m=><div key={m.id}><Avatar mentor={m} small/><span><b>{m.name}</b>{m.role} · {m.college}</span><button onClick={browse}>View profile</button></div>)}</div></div></div>}

function FeatureVisual({type}:{type:'match'|'roadmap'|'session'}){if(type==='match')return <div className="feature-visual match-visual"><div className="match-score"><b>92%</b><span>GOAL FIT</span></div><div className="visual-mentor"><Avatar mentor={mentors[0]}/><span><b>{mentors[0].name}</b>{mentors[0].role}<small>{mentors[0].college} · {mentors[0].company}</small></span></div><div className="fit-bars"><i style={{width:'92%'}}/><i style={{width:'78%'}}/><i style={{width:'86%'}}/></div></div>;if(type==='roadmap')return <div className="feature-visual roadmap-visual"><span>PRODUCT ENGINEER ROADMAP</span>{['Strong foundations','Build credible proof','Interview deliberately','Choose the right offer'].map((x,i)=><div key={x}><b>{i+1}</b><p>{x}<small>{['DSA · Web systems · Git','2 production-grade projects','Mocks · stories · system design','Team · learning · trajectory'][i]}</small></p><i className={i<2?'done':''}>{i<2?'✓':'○'}</i></div>)}</div>;return <div className="feature-visual session-visual"><div className="session-top"><Avatar mentor={mentors[1]} small/><span><b>Session with Nisha</b>Thu, 24 Jul · 6:00 PM</span><i>30 min</i></div><h3>Your focus</h3><div className="agenda"><span>01</span><p>Portfolio positioning</p><span>02</span><p>Product interview stories</p><span>03</span><p>Next 30-day action plan</p></div><button>Join mentor session →</button></div>}

function FAQ(){const [open,setOpen]=useState(0);const items=[['Who is VantiqLabs for?','Engineering students who want practical, college-relevant career guidance—and alumni who want to share experience through roadmaps and focused mentorship.'],['How are mentors verified?','The MVP verifies college affiliation and professional experience before a mentor becomes discoverable. Verification details stay visible on every profile.'],['Which colleges are live?','BMSIT&M and MSRIT are live first. BIT, DSCE, NMIT, Sir. MVIT, Presidency University, JSS, RVCE, and CMRIT are available for early-access registration.'],['What can I ask a mentor about?','Career planning, projects, portfolios, resumes, interviews, role transitions, company selection, and the decisions that generic online content cannot answer for you.'],['Do I need to pay to explore mentors?','Browsing mentors and previewing their profiles is free. Paid sessions and premium roadmaps display pricing clearly before checkout.'],['Can alumni choose their availability?','Yes. Mentors control their schedule, session topics, pricing, and whether their profile is visible.']];return <section className="faq-section" id="faq"><div className="editorial-heading"><span>QUESTIONS, ANSWERED</span><h2>Frequently asked questions.</h2></div><div className="faq-list">{items.map(([q,a],i)=><article className={open===i?'open':''} key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><b>{q}</b><i>{open===i?'−':'↓'}</i></button><div><p>{a}</p></div></article>)}</div></section>}

function MentorOrbit({browse}:{browse:()=>void}){const portraits=['/assets/mentor-airbus.png','/assets/mentor-google.png','/assets/mentor-product.png','/assets/mentor-data.png'];return <section className="mentor-orbit"><div className="orbit-ring ring-one">{portraits.map((src,i)=><img key={src} src={src} alt={['Airbus aerospace mentor','Google software mentor','Product management mentor','Data science mentor'][i]}/>)}</div><div className="orbit-ring ring-two">{[...portraits].reverse().map((src,i)=><img key={`${src}-two`} src={src} alt="VantiqLabs mentor"/>)}</div><div className="orbit-center"><span>PEOPLE, NOT NOISE</span><h2>Career clarity is<br/>closer than it feels.</h2><p>Meet alumni who understand your starting point and can help you choose the next move.</p><button className="dark-cta" onClick={browse}>Meet your mentors →</button></div></section>}

function AuthScreen({mode,switchMode,back}:{mode:'signin'|'signup';switchMode:(mode:'signin'|'signup')=>void;back:()=>void}){const [theme,setTheme]=useState<'light'|'dark'>('dark'),[show,setShow]=useState(false);const signup=mode==='signup';return <main className={`auth-page ${theme}`}><button className="auth-brand" onClick={back}>✦ VantiqLabs</button><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?'☀':'☾'}<span>{theme==='dark'?'Light':'Dark'} mode</span></button><section className="auth-card"><div className="auth-kicker">{signup?'START YOUR VANTIQ JOURNEY':'WELCOME BACK'}</div><h1>{signup?'Create your account':'Sign in to VantiqLabs'}</h1><p>{signup?'Already have an account?':'New to VantiqLabs?'} <button onClick={()=>switchMode(signup?'signin':'signup')}>{signup?'Sign in':'Create an account'}</button></p><form onSubmit={e=>e.preventDefault()}>{signup&&<label>Full name<input required placeholder="Enter your full name"/></label>}<label>College email<input required type="email" placeholder="you@college.edu"/></label><label>Password<div className="password-field"><input required type={show?'text':'password'} placeholder={signup?'Create a password':'Enter your password'}/><button type="button" onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div></label>{signup&&<label>College<select defaultValue=""><option value="" disabled>Select your college</option><option>BMSIT&M</option><option>MSRIT</option><option>Other / Coming soon</option></select></label>}<button className="auth-submit" type="submit">{signup?'Create your account':'Sign in to your account'} →</button></form><div className="auth-divider"><span>OR CONTINUE WITH</span></div><button className="social-auth"><b className="google-g">G</b>Continue with Google</button><p className="auth-terms">By continuing, you agree to VantiqLabs' Terms and Privacy Policy.</p></section></main>}
function MentorBubble({mentor,label}:{mentor:Mentor;label:string}){return <div className="bubble"><Avatar mentor={mentor} small/><div><b>{mentor.name}</b><span>{label}</span></div><i>✓</i></div>}
function MentorCard({mentor,go,save,toggle}:{mentor:Mentor;go:()=>void;save?:boolean;toggle?:()=>void}){return <article className="mentor-card"><div className="card-top"><Avatar mentor={mentor}/>{toggle&&<button className={'save '+(save?'on':'')} onClick={toggle}>♥</button>}</div><button className="card-body" onClick={go}><div className="verified">✓ VERIFIED MENTOR</div><h3>{mentor.name}</h3><p>{mentor.role} · <b>{mentor.company}</b></p><span className="college-pill">{mentor.college}</span><div className="tags">{mentor.expertise.map(x=><span key={x}>{x}</span>)}</div><div className="card-bottom"><span>★ {mentor.rating} · {mentor.years}</span><b>View profile →</b></div></button></article>}

function Browse({query,setQuery,college,setCollege,goProfile,saved,toggleSave,setSoon}:{query:string;setQuery:(x:string)=>void;college:string;setCollege:(x:string)=>void;goProfile:(m:Mentor)=>void;saved:number[];toggleSave:(n:number)=>void;setSoon:(n:string)=>void}){
 const filtered=useMemo(()=>mentors.filter(m=>(college==='All colleges'||m.college===college)&&`${m.name} ${m.role} ${m.company} ${m.expertise.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[query,college])
 const choose=(x:string)=>{setCollege(x);if(x!=='All colleges'&&!liveColleges.includes(x as never))setSoon(x)}
 return <main className="app-shell"><aside className="filter-panel"><p className="section-kicker">DISCOVER</p><h2>Find your mentor</h2><label>College</label><button className={college==='All colleges'?'filter active':'filter'} onClick={()=>choose('All colleges')}>All colleges</button>{liveColleges.map(x=><button className={college===x?'filter active':'filter'} onClick={()=>choose(x)} key={x}>{x}<span>Live</span></button>)}<label>Other campuses</label>{comingColleges.map(([x])=><button className="filter muted-filter" onClick={()=>choose(x)} key={x}>{x}<span>Soon</span></button>)}</aside><section className="browse-content"><div className="browse-heading"><div><p className="section-kicker">VERIFIED PEOPLE, PRACTICAL ADVICE</p><h1>Explore mentors</h1></div><span>{filtered.length} mentors</span></div><div className="search-wide"><Icon>⌕</Icon><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, role, company, or skill"/><button onClick={()=>setQuery('')}>Clear</button></div><div className="chip-row"><button className="chip active">All expertise</button><button className="chip">Engineering</button><button className="chip">Product</button><button className="chip">Design</button><button className="chip">Data</button></div>{filtered.length?<div className="mentor-grid all">{filtered.map(m=><MentorCard key={m.id} mentor={m} go={()=>goProfile(m)} save={saved.includes(m.id)} toggle={()=>toggleSave(m.id)}/>)}</div>:<div className="empty"><b>No mentors match that search.</b><p>Try a broader skill, role, or company.</p></div>}</section></main>
}

function Profile({mentor,back,book,saved,toggleSave}:{mentor:Mentor;back:()=>void;book:()=>void;saved:boolean;toggleSave:()=>void}){const [tab,setTab]=useState('Overview');return <main className="profile"><button className="back" onClick={back}>← Back to mentors</button><section className="profile-hero"><div className="profile-copy"><div className="verified">✓ VERIFIED VANTIQ MENTOR</div><h1>{mentor.name}</h1><p>{mentor.role} at <b>{mentor.company}</b> · {mentor.college}</p><div className="profile-metrics"><span>★ {mentor.rating} rating</span><span>{mentor.years} experience</span><span>42 sessions</span></div></div><Avatar mentor={mentor}/></section><div className="profile-layout"><section><div className="tabs">{['Overview','Career roadmap','Interview prep','Resources'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}</button>)}</div>{tab==='Overview'?<><h2>Make your next move with clarity.</h2><p className="profile-text">{mentor.name.split(' ')[0]} helps students turn uncertainty into a focused career plan. Expect straightforward feedback, practical resources, and a perspective shaped by real experience.</p><div className="info-grid"><div><span>EXPERTISE</span><p>{mentor.expertise.join(' · ')}</p></div><div><span>ALUMNI NETWORK</span><p>{mentor.college}</p></div></div><h2>What you can learn</h2><div className="learn-list"><div><b>Career roadmap</b><span>A concrete plan from where you are to where you want to be.</span></div><div><b>Interview preparation</b><span>Practice that mirrors the conversations you will actually have.</span></div><div><b>Portfolio feedback</b><span>Honest review of the work that represents you.</span></div></div></>:<Locked tab={tab}/>}</section><aside className="book-card"><span>1:1 MENTOR SESSION</span><h3>Get practical advice from {mentor.name.split(' ')[0]}.</h3><p>30 minutes · Video call</p><div className="price">₹{mentor.rate}<small> / session</small></div><button className="btn full" onClick={book}>Book a session →</button><button className="secondary full" onClick={toggleSave}>{saved?'♥ Saved to your list':'♡ Save mentor'}</button><p className="fine">Secure checkout · Cancel up to 24 hours before</p></aside></div><div className="mobile-cta"><button className="btn full" onClick={book}>Book for ₹{mentor.rate} →</button></div></main>}
function Locked({tab}:{tab:string}){return <div className="locked"><span>✦ VantiqLabs Pro</span><h2>{tab} built from lived experience.</h2><p>This mentor has shared their personal playbook. Unlock a roadmap or book a session to see it.</p><button className="btn">Unlock the full view →</button></div>}

function Booking({mentor,done}:{mentor:Mentor;done:()=>void}){const [step,setStep]=useState(1),[date,setDate]=useState('Thu, 24 Jul'),[time,setTime]=useState('6:00 PM');if(step===4)return <main className="booking"><div className="confirmation"><div className="success">✓</div><p className="section-kicker">BOOKING CONFIRMED</p><h1>You’re all set.</h1><p>Your session with {mentor.name} is confirmed for {date} at {time}. A calendar invite is on its way.</p><button className="btn" onClick={done}>Go to my dashboard →</button></div></main>;return <main className="booking"><button className="back" onClick={()=>history.back()}>← Back</button><div className="progress">{['Choose a time','Review','Payment'].map((x,i)=><div className={step===i+1?'active':step>i+1?'complete':''} key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><div className="booking-grid"><section><p className="section-kicker">SESSION WITH {mentor.name.toUpperCase()}</p>{step===1&&<><h1>Choose a time that works.</h1><div className="date-row">{['Tue, 22 Jul','Wed, 23 Jul','Thu, 24 Jul','Fri, 25 Jul'].map(x=><button className={date===x?'selected':''} onClick={()=>setDate(x)} key={x}>{x}</button>)}</div><h3>Available times · {date}</h3><div className="slots">{['10:00 AM','11:30 AM','2:00 PM','4:30 PM','6:00 PM','7:30 PM'].map(x=><button className={time===x?'selected':''} onClick={()=>setTime(x)} key={x}>{x}</button>)}</div></>}{step===2&&<><h1>Review your session.</h1><div className="review"><b>30-minute mentorship session</b><p>{date} · {time}</p><p>Video meeting link sent after payment.</p></div></>}{step===3&&<><h1>Secure payment.</h1><div className="pay-form"><label>Cardholder name<input placeholder="Your full name"/></label><label>Card number<input placeholder="1234 1234 1234 1234"/></label><div><label>Expiry<input placeholder="MM / YY"/></label><label>CVV<input placeholder="•••"/></label></div><p className="fine">Prototype checkout — no payment will be processed.</p></div></>}<button className="btn next" onClick={()=>setStep(step===3?4:step+1)}>{step===3?`Pay ₹${mentor.rate} securely →`:'Continue →'}</button></section><aside className="summary"><Avatar mentor={mentor} small/><h3>{mentor.name}</h3><p>{mentor.role} · {mentor.company}</p><hr/><div><span>Mentor session</span><b>₹{mentor.rate}</b></div><div><span>Platform fee</span><b>₹0</b></div><hr/><div className="total"><b>Total</b><b>₹{mentor.rate}</b></div></aside></div></main>}

function Dashboard({goBrowse,goProfile,saved}:{goBrowse:()=>void;goProfile:(m:Mentor)=>void;saved:number[]}){return <main className="dashboard"><aside className="dash-side"><b>✦ VantiqLabs</b><button className="active">Overview</button><button onClick={goBrowse}>Explore mentors</button><button>My sessions</button><button>Saved mentors <span>{saved.length}</span></button><button>Learning plan</button></aside><section className="dash-main"><p className="section-kicker">THURSDAY, 17 JULY</p><h1>Good morning, Pragy. <em>Keep going.</em></h1><div className="goal"><div><span>YOUR CAREER GOAL</span><h2>Become a product engineer</h2><p>3 of 5 milestones completed</p></div><b>60%</b></div><div className="dash-head"><h2>Recommended for you</h2><button className="text-btn" onClick={goBrowse}>Explore all →</button></div><div className="mentor-grid">{mentors.slice(0,3).map(m=><MentorCard key={m.id} mentor={m} go={()=>goProfile(m)}/>)}</div><div className="dash-head"><h2>Upcoming sessions</h2></div><div className="session"><div className="calendar"><b>24</b><span>JUL</span></div><div><b>Product careers with Nisha Rao</b><p>Thursday · 6:00 PM · Video call</p></div><button className="secondary">Join when ready</button></div></section></main>}
function ComingSoon({name,close}:{name:string;close:()=>void}){const [sent,setSent]=useState(false);return <div className="modal-wrap"><div className="modal"><button className="close" onClick={close}>×</button><div className="soon-icon">✦</div><p className="section-kicker">{name.toUpperCase()}</p><h2>We’re building your mentor network.</h2><p>VantiqLabs is not live at {name} yet. Leave your email and we’ll tell you when mentors from your campus join.</p>{sent?<div className="notice">✓ You’re on the early-access list.</div>:<div className="notify"><input type="email" placeholder="you@college.edu"/><button className="btn" onClick={()=>setSent(true)}>Notify me</button></div>}</div></div>}
